//------------------------------------------------------------------------------
// <auto-generated>
//     Dieser Code wurde von einem Tool generiert.
//     Laufzeitversion:4.0.30319.42000
//
//     Änderungen an dieser Datei können falsches Verhalten verursachen und gehen verloren, wenn
//     der Code erneut generiert wird.
// </auto-generated>
//------------------------------------------------------------------------------

namespace JasonsRPGCharacterTool.Properties {
    using System;
    
    
    /// <summary>
    ///   Eine stark typisierte Ressourcenklasse zum Suchen von lokalisierten Zeichenfolgen usw.
    /// </summary>
    // Diese Klasse wurde von der StronglyTypedResourceBuilder automatisch generiert
    // -Klasse über ein Tool wie ResGen oder Visual Studio automatisch generiert.
    // Um einen Member hinzuzufügen oder zu entfernen, bearbeiten Sie die .ResX-Datei und führen dann ResGen
    // mit der /str-Option erneut aus, oder Sie erstellen Ihr VS-Projekt neu.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Gibt die zwischengespeicherte ResourceManager-Instanz zurück, die von dieser Klasse verwendet wird.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("JasonsRPGCharacterTool.Properties.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Überschreibt die CurrentUICulture-Eigenschaft des aktuellen Threads für alle
        ///   Ressourcenzuordnungen, die diese stark typisierte Ressourcenklasse verwenden.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Class ähnelt.
        /// </summary>
        internal static string applyClassButton {
            get {
                return ResourceManager.GetString("applyClassButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Apply Stats ähnelt.
        /// </summary>
        internal static string applyStats {
            get {
                return ResourceManager.GetString("applyStats", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Costs of Upgrades ähnelt.
        /// </summary>
        internal static string calculateCostsOfUpgrades {
            get {
                return ResourceManager.GetString("calculateCostsOfUpgrades", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculate Damage ähnelt.
        /// </summary>
        internal static string calculateDamage {
            get {
                return ResourceManager.GetString("calculateDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Characters ähnelt.
        /// </summary>
        internal static string characterButtonText {
            get {
                return ResourceManager.GetString("characterButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Acting: ähnelt.
        /// </summary>
        internal static string charActing {
            get {
                return ResourceManager.GetString("charActing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Age: ähnelt.
        /// </summary>
        internal static string charAgeText {
            get {
                return ResourceManager.GetString("charAgeText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Agility: ähnelt.
        /// </summary>
        internal static string charAgilityText {
            get {
                return ResourceManager.GetString("charAgilityText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alchemy: ähnelt.
        /// </summary>
        internal static string charAlchemyText {
            get {
                return ResourceManager.GetString("charAlchemyText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Alteration: ähnelt.
        /// </summary>
        internal static string charAlterationText {
            get {
                return ResourceManager.GetString("charAlterationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Archery: ähnelt.
        /// </summary>
        internal static string charArcheryText {
            get {
                return ResourceManager.GetString("charArcheryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attack Talents ähnelt.
        /// </summary>
        internal static string charAttackTalents {
            get {
                return ResourceManager.GetString("charAttackTalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Base: ähnelt.
        /// </summary>
        internal static string charAttribBaseText {
            get {
                return ResourceManager.GetString("charAttribBaseText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bonus: ähnelt.
        /// </summary>
        internal static string charAttribBonusText {
            get {
                return ResourceManager.GetString("charAttribBonusText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Attributes ähnelt.
        /// </summary>
        internal static string charAttribText {
            get {
                return ResourceManager.GetString("charAttribText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Charisma: ähnelt.
        /// </summary>
        internal static string charChariText {
            get {
                return ResourceManager.GetString("charChariText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Concentration: ähnelt.
        /// </summary>
        internal static string charConcentText {
            get {
                return ResourceManager.GetString("charConcentText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Conjuration: ähnelt.
        /// </summary>
        internal static string charConjurationText {
            get {
                return ResourceManager.GetString("charConjurationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Crafting: ähnelt.
        /// </summary>
        internal static string charCraftingText {
            get {
                return ResourceManager.GetString("charCraftingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        internal static string charCreditsText {
            get {
                return ResourceManager.GetString("charCreditsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Destruction: ähnelt.
        /// </summary>
        internal static string charDestructionText {
            get {
                return ResourceManager.GetString("charDestructionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dexterity: ähnelt.
        /// </summary>
        internal static string charDexterText {
            get {
                return ResourceManager.GetString("charDexterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Drinking: ähnelt.
        /// </summary>
        internal static string charDrinkingText {
            get {
                return ResourceManager.GetString("charDrinkingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Electr. Resistance: ähnelt.
        /// </summary>
        internal static string charElectResText {
            get {
                return ResourceManager.GetString("charElectResText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enchanting: ähnelt.
        /// </summary>
        internal static string charEnchantingText {
            get {
                return ResourceManager.GetString("charEnchantingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endurance: ähnelt.
        /// </summary>
        internal static string charEnduraText {
            get {
                return ResourceManager.GetString("charEnduraText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Endurance: ähnelt.
        /// </summary>
        internal static string charEndurText {
            get {
                return ResourceManager.GetString("charEndurText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fire Resistance: ähnelt.
        /// </summary>
        internal static string charFireResText {
            get {
                return ResourceManager.GetString("charFireResText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Frost Resistance: ähnelt.
        /// </summary>
        internal static string charFrostResText {
            get {
                return ResourceManager.GetString("charFrostResText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Gender: ähnelt.
        /// </summary>
        internal static string charGenderText {
            get {
                return ResourceManager.GetString("charGenderText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon: ähnelt.
        /// </summary>
        internal static string charGun {
            get {
                return ResourceManager.GetString("charGun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon Bonus: ähnelt.
        /// </summary>
        internal static string charGunBonus {
            get {
                return ResourceManager.GetString("charGunBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon Damage: ähnelt.
        /// </summary>
        internal static string charGunDmg {
            get {
                return ResourceManager.GetString("charGunDmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Guns: ähnelt.
        /// </summary>
        internal static string charGuns {
            get {
                return ResourceManager.GetString("charGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hacking: ähnelt.
        /// </summary>
        internal static string charHacking {
            get {
                return ResourceManager.GetString("charHacking", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Heavy Weapons: ähnelt.
        /// </summary>
        internal static string charHeavWeapText {
            get {
                return ResourceManager.GetString("charHeavWeapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Height: ähnelt.
        /// </summary>
        internal static string charHeightText {
            get {
                return ResourceManager.GetString("charHeightText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ship Hit Ch.: ähnelt.
        /// </summary>
        internal static string charHitChance {
            get {
                return ResourceManager.GetString("charHitChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP Current: ähnelt.
        /// </summary>
        internal static string charHPCurrText {
            get {
                return ResourceManager.GetString("charHPCurrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP Max: ähnelt.
        /// </summary>
        internal static string charHPMaxText {
            get {
                return ResourceManager.GetString("charHPMaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Illusion: ähnelt.
        /// </summary>
        internal static string charIllusionText {
            get {
                return ResourceManager.GetString("charIllusionText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Infantry: ähnelt.
        /// </summary>
        internal static string charInfantery {
            get {
                return ResourceManager.GetString("charInfantery", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Initative: ähnelt.
        /// </summary>
        internal static string charInitText {
            get {
                return ResourceManager.GetString("charInitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intelligence: ähnelt.
        /// </summary>
        internal static string charIntelliText {
            get {
                return ResourceManager.GetString("charIntelliText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Intel ähnelt.
        /// </summary>
        internal static string charIntelText {
            get {
                return ResourceManager.GetString("charIntelText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fornsh: ähnelt.
        /// </summary>
        internal static string charLangFornsh {
            get {
                return ResourceManager.GetString("charLangFornsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Løp: ähnelt.
        /// </summary>
        internal static string charLangLop {
            get {
                return ResourceManager.GetString("charLangLop", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mekish: ähnelt.
        /// </summary>
        internal static string charLangMekish {
            get {
                return ResourceManager.GetString("charLangMekish", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die USL: ähnelt.
        /// </summary>
        internal static string charLangUSL {
            get {
                return ResourceManager.GetString("charLangUSL", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Vulsh: ähnelt.
        /// </summary>
        internal static string charLangVulsh {
            get {
                return ResourceManager.GetString("charLangVulsh", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Leading: ähnelt.
        /// </summary>
        internal static string charLeading {
            get {
                return ResourceManager.GetString("charLeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Light Weapons: ähnelt.
        /// </summary>
        internal static string charLightWeapText {
            get {
                return ResourceManager.GetString("charLightWeapText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lockpicking: ähnelt.
        /// </summary>
        internal static string charLockpickText {
            get {
                return ResourceManager.GetString("charLockpickText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Luck: ähnelt.
        /// </summary>
        internal static string charLuckText {
            get {
                return ResourceManager.GetString("charLuckText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lying: ähnelt.
        /// </summary>
        internal static string charLying {
            get {
                return ResourceManager.GetString("charLying", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Mag. Armor: ähnelt.
        /// </summary>
        internal static string charMagArmText {
            get {
                return ResourceManager.GetString("charMagArmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magicka Current: ähnelt.
        /// </summary>
        internal static string charMagCurrText {
            get {
                return ResourceManager.GetString("charMagCurrText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Magicka Max: ähnelt.
        /// </summary>
        internal static string charMagMaxText {
            get {
                return ResourceManager.GetString("charMagMaxText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medicine: ähnelt.
        /// </summary>
        internal static string charMedicine {
            get {
                return ResourceManager.GetString("charMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Monster: ähnelt.
        /// </summary>
        internal static string charMonsterText {
            get {
                return ResourceManager.GetString("charMonsterText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string charNameText {
            get {
                return ResourceManager.GetString("charNameText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Notes ähnelt.
        /// </summary>
        internal static string charNotesText {
            get {
                return ResourceManager.GetString("charNotesText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outfit: ähnelt.
        /// </summary>
        internal static string charOutfit {
            get {
                return ResourceManager.GetString("charOutfit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outfit Bonus: ähnelt.
        /// </summary>
        internal static string charOutfitBonus {
            get {
                return ResourceManager.GetString("charOutfitBonus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outfit Resist: ähnelt.
        /// </summary>
        internal static string charOutfitResist {
            get {
                return ResourceManager.GetString("charOutfitResist", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Outfit Upgrade: ähnelt.
        /// </summary>
        internal static string charOutfitUpgrade {
            get {
                return ResourceManager.GetString("charOutfitUpgrade", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parry: ähnelt.
        /// </summary>
        internal static string charParryText {
            get {
                return ResourceManager.GetString("charParryText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Perception: ähnelt.
        /// </summary>
        internal static string charPerceptText {
            get {
                return ResourceManager.GetString("charPerceptText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Phys. Armor: ähnelt.
        /// </summary>
        internal static string charPhysArmText {
            get {
                return ResourceManager.GetString("charPhysArmText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Pickpocket: ähnelt.
        /// </summary>
        internal static string charPickpocketText {
            get {
                return ResourceManager.GetString("charPickpocketText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Points spent: ähnelt.
        /// </summary>
        internal static string charPointsSpent {
            get {
                return ResourceManager.GetString("charPointsSpent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Poison Resistance: ähnelt.
        /// </summary>
        internal static string charPoisResText {
            get {
                return ResourceManager.GetString("charPoisResText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Practical Talents ähnelt.
        /// </summary>
        internal static string charPracticalTalents {
            get {
                return ResourceManager.GetString("charPracticalTalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Race: ähnelt.
        /// </summary>
        internal static string charRaceText {
            get {
                return ResourceManager.GetString("charRaceText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Repairing: ähnelt.
        /// </summary>
        internal static string charRepairing {
            get {
                return ResourceManager.GetString("charRepairing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Restoration: ähnelt.
        /// </summary>
        internal static string charRestorationText {
            get {
                return ResourceManager.GetString("charRestorationText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Parry: ähnelt.
        /// </summary>
        internal static string charRollReqText {
            get {
                return ResourceManager.GetString("charRollReqText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Searching: ähnelt.
        /// </summary>
        internal static string charSearching {
            get {
                return ResourceManager.GetString("charSearching", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ship Control: ähnelt.
        /// </summary>
        internal static string charShipControl {
            get {
                return ResourceManager.GetString("charShipControl", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Singing: ähnelt.
        /// </summary>
        internal static string charSingingText {
            get {
                return ResourceManager.GetString("charSingingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP Regen: ähnelt.
        /// </summary>
        internal static string charSleepHPRegen {
            get {
                return ResourceManager.GetString("charSleepHPRegen", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Smithing: ähnelt.
        /// </summary>
        internal static string charSmithingText {
            get {
                return ResourceManager.GetString("charSmithingText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sneak: ähnelt.
        /// </summary>
        internal static string charSneakText {
            get {
                return ResourceManager.GetString("charSneakText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Social Talents ähnelt.
        /// </summary>
        internal static string charSocialTalents {
            get {
                return ResourceManager.GetString("charSocialTalents", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Space Combat: ähnelt.
        /// </summary>
        internal static string charSpaceCombat {
            get {
                return ResourceManager.GetString("charSpaceCombat", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Speech: ähnelt.
        /// </summary>
        internal static string charSpeechText {
            get {
                return ResourceManager.GetString("charSpeechText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strength: ähnelt.
        /// </summary>
        internal static string charStrengthAsterius {
            get {
                return ResourceManager.GetString("charStrengthAsterius", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Strength: ähnelt.
        /// </summary>
        internal static string charStrengthText {
            get {
                return ResourceManager.GetString("charStrengthText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Style: ähnelt.
        /// </summary>
        internal static string charStyleText {
            get {
                return ResourceManager.GetString("charStyleText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Talents ähnelt.
        /// </summary>
        internal static string charTalentsText {
            get {
                return ResourceManager.GetString("charTalentsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Throwing: ähnelt.
        /// </summary>
        internal static string charThrowText {
            get {
                return ResourceManager.GetString("charThrowText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trading: ähnelt.
        /// </summary>
        internal static string charTrading {
            get {
                return ResourceManager.GetString("charTrading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Trapping: ähnelt.
        /// </summary>
        internal static string charTrapsText {
            get {
                return ResourceManager.GetString("charTrapsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Unarmed: ähnelt.
        /// </summary>
        internal static string charUnarmedText {
            get {
                return ResourceManager.GetString("charUnarmedText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Please choose the RPG you play. ähnelt.
        /// </summary>
        internal static string chooseRPG {
            get {
                return ResourceManager.GetString("chooseRPG", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to clear the stats of this character? ähnelt.
        /// </summary>
        internal static string clearButton {
            get {
                return ResourceManager.GetString("clearButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Clear character? ähnelt.
        /// </summary>
        internal static string clearButtonHeading {
            get {
                return ResourceManager.GetString("clearButtonHeading", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Companion 1 ähnelt.
        /// </summary>
        internal static string companionChar1Name {
            get {
                return ResourceManager.GetString("companionChar1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Companion 2 ähnelt.
        /// </summary>
        internal static string companionChar2Name {
            get {
                return ResourceManager.GetString("companionChar2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Companion 3 ähnelt.
        /// </summary>
        internal static string companionChar3Name {
            get {
                return ResourceManager.GetString("companionChar3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Credits ähnelt.
        /// </summary>
        internal static string creditsButtonText {
            get {
                return ResourceManager.GetString("creditsButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Programmed and designed by: ähnelt.
        /// </summary>
        internal static string creditsText {
            get {
                return ResourceManager.GetString("creditsText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll Dice ähnelt.
        /// </summary>
        internal static string customRollButtonText {
            get {
                return ResourceManager.GetString("customRollButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Custom Dice Roll ähnelt.
        /// </summary>
        internal static string customRollText {
            get {
                return ResourceManager.GetString("customRollText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Dealt Damage ähnelt.
        /// </summary>
        internal static string dealtDamage {
            get {
                return ResourceManager.GetString("dealtDamage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemy 1 ähnelt.
        /// </summary>
        internal static string enemyChar1Name {
            get {
                return ResourceManager.GetString("enemyChar1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemy 2 ähnelt.
        /// </summary>
        internal static string enemyChar2Name {
            get {
                return ResourceManager.GetString("enemyChar2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemy 3 ähnelt.
        /// </summary>
        internal static string enemyChar3Name {
            get {
                return ResourceManager.GetString("enemyChar3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemy 4 ähnelt.
        /// </summary>
        internal static string enemyChar4Name {
            get {
                return ResourceManager.GetString("enemyChar4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemy 5 ähnelt.
        /// </summary>
        internal static string enemyChar5Name {
            get {
                return ResourceManager.GetString("enemyChar5Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemy 6 ähnelt.
        /// </summary>
        internal static string enemyChar6Name {
            get {
                return ResourceManager.GetString("enemyChar6Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemy 7 ähnelt.
        /// </summary>
        internal static string enemyChar7Name {
            get {
                return ResourceManager.GetString("enemyChar7Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Enemy 8 ähnelt.
        /// </summary>
        internal static string enemyChar8Name {
            get {
                return ResourceManager.GetString("enemyChar8Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Quit ähnelt.
        /// </summary>
        internal static string exitText {
            get {
                return ResourceManager.GetString("exitText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ideal pic ratio: 3x4 ähnelt.
        /// </summary>
        internal static string idealPiceSizeInfoText {
            get {
                return ResourceManager.GetString("idealPiceSizeInfoText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knowledge (Max: 5 Points) ähnelt.
        /// </summary>
        internal static string knowledge {
            get {
                return ResourceManager.GetString("knowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Architecture ähnelt.
        /// </summary>
        internal static string knowledgeArchitecture {
            get {
                return ResourceManager.GetString("knowledgeArchitecture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Astronomy ähnelt.
        /// </summary>
        internal static string knowledgeAstronomy {
            get {
                return ResourceManager.GetString("knowledgeAstronomy", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Bionic ähnelt.
        /// </summary>
        internal static string knowledgeBionic {
            get {
                return ResourceManager.GetString("knowledgeBionic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Computers ähnelt.
        /// </summary>
        internal static string knowledgeComputers {
            get {
                return ResourceManager.GetString("knowledgeComputers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Criminality ähnelt.
        /// </summary>
        internal static string knowledgeCriminality {
            get {
                return ResourceManager.GetString("knowledgeCriminality", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Explosives ähnelt.
        /// </summary>
        internal static string knowledgeExplosives {
            get {
                return ResourceManager.GetString("knowledgeExplosives", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Firearms ähnelt.
        /// </summary>
        internal static string knowledgeGuns {
            get {
                return ResourceManager.GetString("knowledgeGuns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die History ähnelt.
        /// </summary>
        internal static string knowledgeHistory {
            get {
                return ResourceManager.GetString("knowledgeHistory", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Medicine ähnelt.
        /// </summary>
        internal static string knowledgeMedicine {
            get {
                return ResourceManager.GetString("knowledgeMedicine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Military ähnelt.
        /// </summary>
        internal static string knowledgeMilitary {
            get {
                return ResourceManager.GetString("knowledgeMilitary", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Plants ähnelt.
        /// </summary>
        internal static string knowledgePlants {
            get {
                return ResourceManager.GetString("knowledgePlants", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Politics ähnelt.
        /// </summary>
        internal static string knowledgePolitics {
            get {
                return ResourceManager.GetString("knowledgePolitics", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Sciences ähnelt.
        /// </summary>
        internal static string knowledgeSciences {
            get {
                return ResourceManager.GetString("knowledgeSciences", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spaceships ähnelt.
        /// </summary>
        internal static string knowledgeSpaceships {
            get {
                return ResourceManager.GetString("knowledgeSpaceships", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tech ähnelt.
        /// </summary>
        internal static string knowledgeTech {
            get {
                return ResourceManager.GetString("knowledgeTech", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Traps ähnelt.
        /// </summary>
        internal static string knowledgeTraps {
            get {
                return ResourceManager.GetString("knowledgeTraps", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Melee Weapons ähnelt.
        /// </summary>
        internal static string knowledgeUnarmed {
            get {
                return ResourceManager.GetString("knowledgeUnarmed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Languages (Max: 5 Points) ähnelt.
        /// </summary>
        internal static string languages {
            get {
                return ResourceManager.GetString("languages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Lasers ähnelt.
        /// </summary>
        internal static string Lasers {
            get {
                return ResourceManager.GetString("Lasers", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Open ähnelt.
        /// </summary>
        internal static string loadCharsFromZip {
            get {
                return ResourceManager.GetString("loadCharsFromZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Maximum ähnelt.
        /// </summary>
        internal static string maximumText {
            get {
                return ResourceManager.GetString("maximumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Miniguns ähnelt.
        /// </summary>
        internal static string Miniguns {
            get {
                return ResourceManager.GetString("Miniguns", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Minimum ähnelt.
        /// </summary>
        internal static string minimumText {
            get {
                return ResourceManager.GetString("minimumText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Missiles ähnelt.
        /// </summary>
        internal static string Missiles {
            get {
                return ResourceManager.GetString("Missiles", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Update available! ähnelt.
        /// </summary>
        internal static string newVersion {
            get {
                return ResourceManager.GetString("newVersion", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die No ähnelt.
        /// </summary>
        internal static string no {
            get {
                return ResourceManager.GetString("no", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 1 ähnelt.
        /// </summary>
        internal static string playerChar1Name {
            get {
                return ResourceManager.GetString("playerChar1Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 2 ähnelt.
        /// </summary>
        internal static string playerChar2Name {
            get {
                return ResourceManager.GetString("playerChar2Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 3 ähnelt.
        /// </summary>
        internal static string playerChar3Name {
            get {
                return ResourceManager.GetString("playerChar3Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Player 4 ähnelt.
        /// </summary>
        internal static string playerChar4Name {
            get {
                return ResourceManager.GetString("playerChar4Name", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Railgun ähnelt.
        /// </summary>
        internal static string Railgun {
            get {
                return ResourceManager.GetString("Railgun", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Roll Dice ähnelt.
        /// </summary>
        internal static string rollButtonText {
            get {
                return ResourceManager.GetString("rollButtonText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Click on a dice to roll. ähnelt.
        /// </summary>
        internal static string rollHelpText {
            get {
                return ResourceManager.GetString("rollHelpText", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save? ähnelt.
        /// </summary>
        internal static string save {
            get {
                return ResourceManager.GetString("save", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save ähnelt.
        /// </summary>
        internal static string saveCharsToZip {
            get {
                return ResourceManager.GetString("saveCharsToZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save your shop? ähnelt.
        /// </summary>
        internal static string saveOrNah {
            get {
                return ResourceManager.GetString("saveOrNah", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Do you want to save your current Characters? ähnelt.
        /// </summary>
        internal static string saveToZip {
            get {
                return ResourceManager.GetString("saveToZip", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ammo: ähnelt.
        /// </summary>
        internal static string shipAmmo {
            get {
                return ResourceManager.GetString("shipAmmo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AP: ähnelt.
        /// </summary>
        internal static string shipAP {
            get {
                return ResourceManager.GetString("shipAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AP / Move: ähnelt.
        /// </summary>
        internal static string shipAPTurn {
            get {
                return ResourceManager.GetString("shipAPTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armor ähnelt.
        /// </summary>
        internal static string shipArmor {
            get {
                return ResourceManager.GetString("shipArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Spaceships ähnelt.
        /// </summary>
        internal static string shipButton {
            get {
                return ResourceManager.GetString("shipButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Class ähnelt.
        /// </summary>
        internal static string shipClass {
            get {
                return ResourceManager.GetString("shipClass", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Damage: ähnelt.
        /// </summary>
        internal static string shipDmg {
            get {
                return ResourceManager.GetString("shipDmg", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Fighter Bomber ähnelt.
        /// </summary>
        internal static string shipFighterBomber {
            get {
                return ResourceManager.GetString("shipFighterBomber", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Hit Chance: ähnelt.
        /// </summary>
        internal static string shipHitChance {
            get {
                return ResourceManager.GetString("shipHitChance", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP Current: ähnelt.
        /// </summary>
        internal static string shipHPCurr {
            get {
                return ResourceManager.GetString("shipHPCurr", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die HP Max: ähnelt.
        /// </summary>
        internal static string shipHPMax {
            get {
                return ResourceManager.GetString("shipHPMax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ideal pic ratio: 4x3 ähnelt.
        /// </summary>
        internal static string shipIdealPicRatioInfo {
            get {
                return ResourceManager.GetString("shipIdealPicRatioInfo", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string shipName {
            get {
                return ResourceManager.GetString("shipName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Range: ähnelt.
        /// </summary>
        internal static string shipRange {
            get {
                return ResourceManager.GetString("shipRange", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Loss value: ähnelt.
        /// </summary>
        internal static string shipRangeLoss {
            get {
                return ResourceManager.GetString("shipRangeLoss", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Recon ähnelt.
        /// </summary>
        internal static string shipRecon {
            get {
                return ResourceManager.GetString("shipRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield ähnelt.
        /// </summary>
        internal static string shipShield {
            get {
                return ResourceManager.GetString("shipShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Skills ähnelt.
        /// </summary>
        internal static string shipSkills {
            get {
                return ResourceManager.GetString("shipSkills", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Support Fighter ähnelt.
        /// </summary>
        internal static string shipSupportFighter {
            get {
                return ResourceManager.GetString("shipSupportFighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tankfighter ähnelt.
        /// </summary>
        internal static string shipTankfighter {
            get {
                return ResourceManager.GetString("shipTankfighter", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Tactical Recon ähnelt.
        /// </summary>
        internal static string shiptTactRecon {
            get {
                return ResourceManager.GetString("shiptTactRecon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon ähnelt.
        /// </summary>
        internal static string shipWeapon {
            get {
                return ResourceManager.GetString("shipWeapon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die AP: ähnelt.
        /// </summary>
        internal static string shipWeaponAP {
            get {
                return ResourceManager.GetString("shipWeaponAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name: ähnelt.
        /// </summary>
        internal static string shipWeaponName {
            get {
                return ResourceManager.GetString("shipWeaponName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Amount ähnelt.
        /// </summary>
        internal static string shopAmount {
            get {
                return ResourceManager.GetString("shopAmount", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save Asterius ähnelt.
        /// </summary>
        internal static string shopAsteriusSave {
            get {
                return ResourceManager.GetString("shopAsteriusSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shop ähnelt.
        /// </summary>
        internal static string shopButton {
            get {
                return ResourceManager.GetString("shopButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Load TXT ähnelt.
        /// </summary>
        internal static string shopLoadSave {
            get {
                return ResourceManager.GetString("shopLoadSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Item Name ähnelt.
        /// </summary>
        internal static string shopName {
            get {
                return ResourceManager.GetString("shopName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Price ähnelt.
        /// </summary>
        internal static string shopPrice {
            get {
                return ResourceManager.GetString("shopPrice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Save TES ähnelt.
        /// </summary>
        internal static string shopTESSave {
            get {
                return ResourceManager.GetString("shopTESSave", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Create a shop in the shop tool to be able to later load it in the RPG-mode of your choosing. ähnelt.
        /// </summary>
        internal static string shopToolDescript {
            get {
                return ResourceManager.GetString("shopToolDescript", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Knowledge ähnelt.
        /// </summary>
        internal static string standaloneKnowledge {
            get {
                return ResourceManager.GetString("standaloneKnowledge", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Languages ähnelt.
        /// </summary>
        internal static string standaloneLanguages {
            get {
                return ResourceManager.GetString("standaloneLanguages", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Torpedos ähnelt.
        /// </summary>
        internal static string Torpedos {
            get {
                return ResourceManager.GetString("Torpedos", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shipcomputer Upgrade (AP) ähnelt.
        /// </summary>
        internal static string upgradeAP {
            get {
                return ResourceManager.GetString("upgradeAP", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Ship AP * 10 ähnelt.
        /// </summary>
        internal static string upgradeAPFormula {
            get {
                return ResourceManager.GetString("upgradeAPFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Thruster Upgrade (AP / Move) ähnelt.
        /// </summary>
        internal static string upgradeAPTurn {
            get {
                return ResourceManager.GetString("upgradeAPTurn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (100 - AP / Move) * 40 ähnelt.
        /// </summary>
        internal static string upgradeAPTurnFormula {
            get {
                return ResourceManager.GetString("upgradeAPTurnFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armor Upgrade ähnelt.
        /// </summary>
        internal static string upgradeArmor {
            get {
                return ResourceManager.GetString("upgradeArmor", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Armor * 50 ähnelt.
        /// </summary>
        internal static string upgradeArmorFormula {
            get {
                return ResourceManager.GetString("upgradeArmorFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Calculations ähnelt.
        /// </summary>
        internal static string upgradeButton {
            get {
                return ResourceManager.GetString("upgradeButton", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Formula ähnelt.
        /// </summary>
        internal static string upgradeFormula {
            get {
                return ResourceManager.GetString("upgradeFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Radarsystem Upgrade (Hit Chance) ähnelt.
        /// </summary>
        internal static string upgradeHC {
            get {
                return ResourceManager.GetString("upgradeHC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die (-20 - Hit Chance) * (- 150) ähnelt.
        /// </summary>
        internal static string upgradeHCFormula {
            get {
                return ResourceManager.GetString("upgradeHCFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Input ähnelt.
        /// </summary>
        internal static string upgradeInput {
            get {
                return ResourceManager.GetString("upgradeInput", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Name ähnelt.
        /// </summary>
        internal static string upgradeName {
            get {
                return ResourceManager.GetString("upgradeName", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Result ähnelt.
        /// </summary>
        internal static string upgradeResult {
            get {
                return ResourceManager.GetString("upgradeResult", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield Upgrade ähnelt.
        /// </summary>
        internal static string upgradeShield {
            get {
                return ResourceManager.GetString("upgradeShield", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Shield * 50 ähnelt.
        /// </summary>
        internal static string upgradeShieldFormula {
            get {
                return ResourceManager.GetString("upgradeShieldFormula", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Weapon Type ähnelt.
        /// </summary>
        internal static string weaponType {
            get {
                return ResourceManager.GetString("weaponType", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Sucht eine lokalisierte Zeichenfolge, die Yes ähnelt.
        /// </summary>
        internal static string yes {
            get {
                return ResourceManager.GetString("yes", resourceCulture);
            }
        }
    }
}
